services:
  frontend:
    build: ./frontend
    ports:
      - 3000:80
  mongo:
    image: docker.io/mongo
    volumes:
      - mongoDB:/data/db
  mongo-express:
    image: docker.io/mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
  backend:
    build: ./backend
    ports:
<<<<<<< HEAD
      - 3002:3002
    depends_on:
      - mongo
=======
      - 3002:3002 # REST API
      - 3001:3001 # Websocket
    depends_on:
      - mongo
      - redis
>>>>>>> pemc-helpme
    env_file:
      - .env
  redis:
    image: docker.io/redis

volumes:
  mongoDB:
<<<<<<< HEAD
    external: true
=======
    external: true
>>>>>>> pemc-helpme
