services:
  mongo:
    image: docker.io/mongo
    container_name: mongo
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - ./mongo:/data/db
  mongo-express:
    image: docker.io/mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
    depends_on:
      - mongo
      #environment:
      #  ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #  ME_CONFIG_MONGODB_ADMINPASSWORD: example
      #  ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      #  ME_CONFIG_BASICAUTH: false
      #  redis:
      #    image: docker.io/redis
